### ISSUE TITLE
Tidy up code

### ISSUE THREAD

**Issue by ohnx** [ohnx/c_hashmap#2]
The code is terribly messy atm.

Clean it up and rename some of the vars so that it can be used properly in `ctypes`

**Comment by SpaceKookie** [comment]
I would actually suggest to get the code into this form: http://www.gnu.org/prep/standards/standards.html#Formatting

**Comment by ohnx** [comment]
I actually find having the opening brace for anything on another line makes it harder to read, and would prefer something along the lines of https://users.ece.cmu.edu/~eno/coding/CCodingStandard.html instead.

ie, I find it easier to read and understand
```c
int main() {
    printf("Hello World!");
}
```
instead of
```c
int main()
{
    printf("Hello World!");
}
```
